setting: ssl
lightning_module:
  _target_: src.models.transformers.SSLPretrainedTransformer

# Additional SSL params
model:
  mu: 8  # 4 per GPU
  threshold: 0.95
  lambda_u: 1.0
  ul_branches: 6
  max_ul_batch_size_per_gpu: 65  # taking full ul_batch, if max_ul_batch_size_per_gpu = mu * train.batch_size *  (ul_branches - 1) / n_gpus

exp:
  val_check_interval: 1.0