setting: ssl
lightning_module:
  _target_: src.models.transformers.SSLPretrainedTransformer

# Additional SSL params
model:
  mu: 4  # 4 per GPU
  threshold: 0.95
  lambda_u: 1.0
  ul_branches: 4

exp:
  val_check_interval: 1.0